CFLAGS = `pkg-config --libs --cflags gtk+-2.0 clutter-0.9 clutter-gtk-0.9 gio-2.0`

test-covflow: main-covflow.c clutter-cover-flow.c clutter-black-texture.c
	gcc -g -Wall $(CFLAGS) -o $@ $^

clean:
	rm -f test-covflow
